name: Deploy tested project to GCP

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions: write-all

jobs:
  call-build:
    uses: trevorism/actions-workflows/.github/workflows/build.yml@master
    with:
      JDK_VERSION: 17

  call-deploy:
    uses: trevorism/actions-workflows/.github/workflows/deploy.yml@master
    needs: [call-build]
    with:
      JDK_VERSION: 17
      gcp_project: 'trevorism-draw'
      gcp_project_id: '882208491219'
      version: '0-5-0'
    secrets:
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      SIGNING_KEY: ${{ secrets.SIGNING_KEY }}

  call-accept-after:
    uses: trevorism/actions-workflows/.github/workflows/accept.yml@master
    needs: call-deploy
    with:
      JDK_VERSION: 17